### ISSUE TITLE
IE11 showing popup instead of popunder

### ISSUE THREAD

**Issue by peefg** [hpbuniat/jquery-popunder#66] opened 2015-02-20 07:31 UTC
Can be that fixed please? Working fine in other browsers, but IE makes this issue.

**Comment by hpbuniat** [comment] 2015-04-06 14:12
Worksforme or Dupe of #46

**Closed by hpbuniat** 2015-04-06 14:12 UTC

**Comment by alexkrasov** [comment] 2015-04-15 07:31
I've found out that the "popup instead of popunder" is a version-specific issue at IE11
It DOES works under 11.0.9600.17633 (popunder)
It DOESN'T under 11.0.9600.17691(popup most of the time)
